/**
 * config.js - Global configuration for brag.charity frontend.
 * Auto-generated by scripts/loader.js - DO NOT EDIT MANUALLY.
 */

window.APP_CONFIG = {
    "alchemy": {
        "31337": {
            "apiKey": "LOCAL",
            "gasPolicyId": "",
            "rpcUrl": "http://0.0.0.0:8545",
            "entryPointAddress": "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
            "factoryAddress": "0x000000000019d2Ee9F2729A65AfE20bb0020AefC"
        },
        "11155111": {
            "apiKey": "",
            "gasPolicyId": "",
            "rpcUrl": "https://eth-sepolia.g.alchemy.com/v2/",
            "entryPointAddress": "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
            "factoryAddress": "0x000000000019d2Ee9F2729A65AfE20bb0020AefC"
        }
    },
    "gasLimits": {
        "maxFeePerGas": "100000000000",
        "maxPriorityFeePerGas": "2000000000",
        "hugeCalldataGasLimit": 25000000
    },
    "bridgeUrl": ""
};
