import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
export const ROOT = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(ROOT, 'config.json');

/**
 * Reads config.json and applies process.env overrides
 */
export function loadConfig() {
    let rawConfig = {};
    if (fs.existsSync(CONFIG_PATH)) {
        try {
            rawConfig = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
        } catch (e) {
            console.error(`[loader] Error parsing ${CONFIG_PATH}:`, e.message);
        }
    }

    const appEnv = process.env.APP_ENV || process.env.HARDHAT_NETWORK || rawConfig.env || 'local';
    const chainId = process.env.CHAIN_ID
        ? parseInt(process.env.CHAIN_ID)
        : (appEnv === 'sepolia' ? 11155111 : 31337);

    // Merge env overrides
    const config = {
        env: appEnv,
        chainId: chainId,
        ports: {
            bridgeHttp: parseInt(process.env.BRIDGE_HTTP_PORT || process.env.PORT || rawConfig.ports?.bridgeHttp || 9000),
            bridgeWs: parseInt(process.env.BRIDGE_WS_PORT || process.env.WS_PORT || rawConfig.ports?.bridgeWs || 9001),
            envManager: parseInt(process.env.ENV_MANAGER_PORT || rawConfig.ports?.envManager || 9002),
            frontend: parseInt(process.env.FRONTEND_PORT || rawConfig.ports?.frontend || 3000),
            bedrockManager: parseInt(process.env.BEDROCK_MANAGER_PORT || rawConfig.ports?.bedrockManager || 9003)
        },
        bridge: {
            summonFeeBrag: process.env.SUMMON_FEE_BRAG || rawConfig.bridge?.summonFeeBrag || "10",
            servers: rawConfig.bridge?.servers || {}
        },
        contracts: rawConfig.contracts || {},
        frontend: rawConfig.frontend || {},
        addon: rawConfig.addon || {}
    };

    // Override Alchemy keys from environment if present
    if (process.env.ALCHEMY_API_KEY && config.frontend.alchemy?.['11155111']) {
        config.frontend.alchemy['11155111'].apiKey = process.env.ALCHEMY_API_KEY;
    }
    if (process.env.ALCHEMY_GAS_POLICY_ID && config.frontend.alchemy?.['11155111']) {
        config.frontend.alchemy['11155111'].gasPolicyId = process.env.ALCHEMY_GAS_POLICY_ID;
    }

    // Override Addon parameters from environment if present
    if (process.env.WS_URL) config.addon.wsUrl = process.env.WS_URL;
    if (process.env.SERVER_ID) config.addon.serverId = process.env.SERVER_ID;

    return config;
}

/**
 * Returns contract address with fallback chain:
 * 1. process.env (e.g. CONTRACT_ADDRESS_BRAGNFT)
 * 2. config.json contracts[chainId][contractName]
 * 3. ignition/deployments/chain-{chainId}/deployed_addresses.json
 */
export function getContractAddress(contractName, chainId) {
    const envVar = `CONTRACT_ADDRESS_${contractName.toUpperCase()}`;
    if (process.env[envVar]) return process.env[envVar];

    const config = loadConfig();
    const effectiveChainId = chainId || config.chainId;

    if (config.contracts?.[effectiveChainId]?.[contractName]) {
        return config.contracts[effectiveChainId][contractName];
    }

    const deploymentPath = path.join(ROOT, 'ignition', 'deployments', `chain-${effectiveChainId}`, 'deployed_addresses.json');
    if (fs.existsSync(deploymentPath)) {
        try {
            const deployments = JSON.parse(fs.readFileSync(deploymentPath, 'utf8'));
            return deployments[`AppModule#${contractName}`] || null;
        } catch (e) {
            console.error(`[loader] Error reading deployment file ${deploymentPath}:`, e.message);
        }
    }

    return null;
}

/**
 * Dynamically generates frontend/config.js based on central config
 */
export function generateFrontendConfigJS() {
    const config = loadConfig();
    const frontendContent = `/**
 * config.js - Global configuration for brag.charity frontend.
 * Auto-generated by scripts/loader.js - DO NOT EDIT MANUALLY.
 */

window.APP_CONFIG = ${JSON.stringify(config.frontend, null, 4)};
`;
    const targetPath = path.join(ROOT, 'frontend', 'config.js');
    fs.writeFileSync(targetPath, frontendContent);
    return targetPath;
}

/**
 * Dynamically generates addons/minecraft-bedrock-addon/.../scripts/config.js based on central config
 */
export function generateAddonConfigJS() {
    const config = loadConfig();
    const isStaging = config.env === 'staging';
    const wsUrl = (isStaging ? process.env.STAGING_BRIDGE_URL : null) || process.env.WS_URL || config.addon.wsUrl || 'ws://127.0.0.1:9001';
    const serverId = process.env.SERVER_ID || config.addon.serverId || 'local-dev';

    let nexusAddress = (isStaging ? process.env.STAGING_BRAGNFT_ADDRESS : null) || process.env.CONTRACT_ADDRESS_BRAGNFT || config.addon.nexusAddress;
    if (!nexusAddress || nexusAddress === '0x0000000000000000000000000000000000000000') {
        nexusAddress = getContractAddress('BragNFT', config.chainId) || '0x0000000000000000000000000000000000000000';
    }

    const addonContent = `// Auto-generated by scripts/loader.js - DO NOT EDIT MANUALLY
export const WS_URL = "${wsUrl}";
export const SERVER_ID = "${serverId}";
export const NEXUS_ADDRESS = "${nexusAddress}";
`;

    const targetPath = path.join(
        ROOT,
        'addons',
        'minecraft-bedrock-addon',
        'development_behavior_packs',
        'behavior_pack_sample',
        'scripts',
        'config.js'
    );

    const dir = path.dirname(targetPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(targetPath, addonContent);
    return targetPath;
}
